/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes__/__root'
import { Route as AuthImport } from './routes__/auth'
import { Route as LayoutImport } from './routes__/_layout'
import { Route as IndexImport } from './routes__/index'
import { Route as LayoutEmailTypeIndexImport } from './routes__/_layout/$emailType/index'
import { Route as LayoutEmailTypeAccountIdCategoryIdIndexImport } from './routes__/_layout/$emailType/$accountId/$categoryId/index'
import { Route as LayoutEmailTypeAccountIdCategoryIdEmailIdIndexImport } from './routes__/_layout/$emailType/$accountId/$categoryId/$emailId/index'

// Create/Update Routes

const AuthRoute = AuthImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRoute,
} as any)

const LayoutRoute = LayoutImport.update({
  id: '/_layout',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const LayoutEmailTypeIndexRoute = LayoutEmailTypeIndexImport.update({
  id: '/$emailType/',
  path: '/$emailType/',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutEmailTypeAccountIdCategoryIdIndexRoute =
  LayoutEmailTypeAccountIdCategoryIdIndexImport.update({
    id: '/$emailType/$accountId/$categoryId/',
    path: '/$emailType/$accountId/$categoryId/',
    getParentRoute: () => LayoutRoute,
  } as any)

const LayoutEmailTypeAccountIdCategoryIdEmailIdIndexRoute =
  LayoutEmailTypeAccountIdCategoryIdEmailIdIndexImport.update({
    id: '/$emailType/$accountId/$categoryId/$emailId/',
    path: '/$emailType/$accountId/$categoryId/$emailId/',
    getParentRoute: () => LayoutRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutImport
      parentRoute: typeof rootRoute
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthImport
      parentRoute: typeof rootRoute
    }
    '/_layout/$emailType/': {
      id: '/_layout/$emailType/'
      path: '/$emailType'
      fullPath: '/$emailType'
      preLoaderRoute: typeof LayoutEmailTypeIndexImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/$emailType/$accountId/$categoryId/': {
      id: '/_layout/$emailType/$accountId/$categoryId/'
      path: '/$emailType/$accountId/$categoryId'
      fullPath: '/$emailType/$accountId/$categoryId'
      preLoaderRoute: typeof LayoutEmailTypeAccountIdCategoryIdIndexImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/$emailType/$accountId/$categoryId/$emailId/': {
      id: '/_layout/$emailType/$accountId/$categoryId/$emailId/'
      path: '/$emailType/$accountId/$categoryId/$emailId'
      fullPath: '/$emailType/$accountId/$categoryId/$emailId'
      preLoaderRoute: typeof LayoutEmailTypeAccountIdCategoryIdEmailIdIndexImport
      parentRoute: typeof LayoutImport
    }
  }
}

// Create and export the route tree

interface LayoutRouteChildren {
  LayoutEmailTypeIndexRoute: typeof LayoutEmailTypeIndexRoute
  LayoutEmailTypeAccountIdCategoryIdIndexRoute: typeof LayoutEmailTypeAccountIdCategoryIdIndexRoute
  LayoutEmailTypeAccountIdCategoryIdEmailIdIndexRoute: typeof LayoutEmailTypeAccountIdCategoryIdEmailIdIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutEmailTypeIndexRoute: LayoutEmailTypeIndexRoute,
  LayoutEmailTypeAccountIdCategoryIdIndexRoute:
    LayoutEmailTypeAccountIdCategoryIdIndexRoute,
  LayoutEmailTypeAccountIdCategoryIdEmailIdIndexRoute:
    LayoutEmailTypeAccountIdCategoryIdEmailIdIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '': typeof LayoutRouteWithChildren
  '/auth': typeof AuthRoute
  '/$emailType': typeof LayoutEmailTypeIndexRoute
  '/$emailType/$accountId/$categoryId': typeof LayoutEmailTypeAccountIdCategoryIdIndexRoute
  '/$emailType/$accountId/$categoryId/$emailId': typeof LayoutEmailTypeAccountIdCategoryIdEmailIdIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '': typeof LayoutRouteWithChildren
  '/auth': typeof AuthRoute
  '/$emailType': typeof LayoutEmailTypeIndexRoute
  '/$emailType/$accountId/$categoryId': typeof LayoutEmailTypeAccountIdCategoryIdIndexRoute
  '/$emailType/$accountId/$categoryId/$emailId': typeof LayoutEmailTypeAccountIdCategoryIdEmailIdIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/_layout': typeof LayoutRouteWithChildren
  '/auth': typeof AuthRoute
  '/_layout/$emailType/': typeof LayoutEmailTypeIndexRoute
  '/_layout/$emailType/$accountId/$categoryId/': typeof LayoutEmailTypeAccountIdCategoryIdIndexRoute
  '/_layout/$emailType/$accountId/$categoryId/$emailId/': typeof LayoutEmailTypeAccountIdCategoryIdEmailIdIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | ''
    | '/auth'
    | '/$emailType'
    | '/$emailType/$accountId/$categoryId'
    | '/$emailType/$accountId/$categoryId/$emailId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | ''
    | '/auth'
    | '/$emailType'
    | '/$emailType/$accountId/$categoryId'
    | '/$emailType/$accountId/$categoryId/$emailId'
  id:
    | '__root__'
    | '/'
    | '/_layout'
    | '/auth'
    | '/_layout/$emailType/'
    | '/_layout/$emailType/$accountId/$categoryId/'
    | '/_layout/$emailType/$accountId/$categoryId/$emailId/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LayoutRoute: typeof LayoutRouteWithChildren
  AuthRoute: typeof AuthRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LayoutRoute: LayoutRouteWithChildren,
  AuthRoute: AuthRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_layout",
        "/auth"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_layout": {
      "filePath": "_layout.tsx",
      "children": [
        "/_layout/$emailType/",
        "/_layout/$emailType/$accountId/$categoryId/",
        "/_layout/$emailType/$accountId/$categoryId/$emailId/"
      ]
    },
    "/auth": {
      "filePath": "auth.tsx"
    },
    "/_layout/$emailType/": {
      "filePath": "_layout/$emailType/index.tsx",
      "parent": "/_layout"
    },
    "/_layout/$emailType/$accountId/$categoryId/": {
      "filePath": "_layout/$emailType/$accountId/$categoryId/index.tsx",
      "parent": "/_layout"
    },
    "/_layout/$emailType/$accountId/$categoryId/$emailId/": {
      "filePath": "_layout/$emailType/$accountId/$categoryId/$emailId/index.tsx",
      "parent": "/_layout"
    }
  }
}
ROUTE_MANIFEST_END */
